US004 View Band Role in Job List
Cormac-F/infinite-harmony-api pull request #26
Opened 2023-12-14 09:29 UTC by amchugh689

- Created Band.java
- Created BandDao.java
- Created BandService.java
- Created BandController.java
- Created FailedToGetAllBandsException.java
- Created FailedToGetBandException.java
- Updated JobDao.java

![Screenshot 2023-12-14 at 09 25 56](https://github.com/Cormac-F/infinite-harmony-api/assets/145450798/2e0f69c6-3b66-489f-95f7-fe9b9285b4b1)
![Screenshot 2023-12-14 at 09 26 08](https://github.com/Cormac-F/infinite-harmony-api/assets/145450798/b214c437-45a4-49b6-8b89-3a97af6ee9b4)
![Screenshot 2023-12-14 at 09 26 34](https://github.com/Cormac-F/infinite-harmony-api/assets/145450798/efd87f66-fcdd-4acb-983c-116e5aaebd77)

2023-12-14 10:06 UTC, Cormac-F approved these changes
LGTM

2023-12-14 10:30 UTC, jkelso662 commented
Merge conflicts need sorted!

2023-12-14 10:34 UTC, jkelso662 requested changes
Great feature! Great code. Shame there are no unit tests anywhere 🙃

2023-12-14 10:34 UTC, jkelso662 commented on src/main/java/org/kainos/ea/DropwizardApplication.java
>          // TODO: implement application
You'll not need this comment as you have already implemented this below :)

2023-12-15 13:54 UTC, lullabelle requested changes
checks are failing on this one. Also there is a merge conflict that will need resolved.
Are there any unit tests?

2023-12-18 13:53 UTC, lullabelle approved these changes

2023-12-20 15:51 UTC, jkelso662 approved these changes
Fab

2023-12-20 15:51 UTC, merged